### ISSUE TITLE
HTTPS for yeoman.io

### ISSUE THREAD

**Issue by passy** [yeoman/yeoman.io#529]
I couldn't find an existing issue for this, but I'm sure we've at least discussed this via chat before. We should get a certificate for yeoman.io, but that would require us to host the website ourselves or set up a reverse proxy to the gh-pages. Alternatively, we could use Cloudflare which has worked really well for my personal site.

If we wanted to make use of a ServiceWorker for the page, this would be a prerequisite.

Brought up by this tweet: https://twitter.com/raindevel/status/639573949622394880

**Comment by addyosmani** [comment]
I'm :+1: for using Cloudflare. Quite a few of us use it in the office and it's fairly painless to get setup.

**Comment by sindresorhus** [comment]
:+1:

**Comment by gaboesquivel** [comment]
moving to cloudflare?  or wait for github to implement it? https://github.com/isaacs/github/issues/156

**Comment by zckrs** [comment]
https://letsencrypt.org/howitworks/

[Let's Encrypt](https://letsencrypt.org/) is in public beta.
May be a easy solution.

**Comment by addyosmani** [comment]
I think I need to go through Google domain folks for the changes, but if someone wants to setup Cloudflare I can get DNS updated..or try to :)

**Comment by mischah** [comment]
If we host the websites data on netlify it would just need [one click](https://www.netlify.com/docs/ssl/) to activate SSL via »Let’s Encrypt«. I would love to set this up after #744 is done.

Would require a DNS update to point yeoman.io to netlify. See https://www.netlify.com/docs/custom-domains/

**Comment by mischah** [comment]
Okay, heres the current status:

- [x] Netlify setup. See https://yeoman.netlify.com/ via #744 
- [x] Prepare site to be served via http. See #745 
- [x] Setup netlify to use our own domain (yeoman.io)
- [ ] Update DNS settings
- [ ] Setup SSL via Let’s Encrypt

I’ve added Simon as another admin to the netlify site and could add other team members as well.

**Comment by mischah** [comment]
Hej @addyosmani Guess I need your help for the DNS thing becuase the DNS entry is still pointing to github.com

There are two things to do.

# 1. Add an ANAME, ALIAS, or A record for yeoman.io

There are two options for pointing your root domain at Netlify:

## Recommended:

Use a DNS provider that supports ANAME or ALIAS records, and alias yeoman.io to yeoman.netlify.com. We recommend using NS1 or Netlify’s built-in DNS service for this.

    yeoman.io ALIAS yeoman.netlify.com

## Alternative:

Create an A record for yeoman.io pointing at our load balancer’s IP 104.198.14.52.

    yeoman.io A 104.198.14.52

# 2. Add a CNAME record for www

Create a CNAME record for www pointing at yeoman.netlify.com.
This record is required to redirect automatically from www.yeoman.io to yeoman.io.

    www CNAME yeoman.netlify.com

See [netlify docs](https://www.netlify.com/docs/custom-domains/#dns-configuration) for more information.

**Comment by addyosmani** [comment]
Hey @mischah. As we registered the original domain through Google's domains team, I've gone ahead and filed a new request with them to make the relevant changes to reference Netlify per your last comment. It can take a few days/week for them to get back to folks, but I'll try to chase getting this updated as quickly as we can.

Thanks for sharing the instructions!

**Comment by mischah** [comment]
Super, thanks for taking care 👌

**Comment by mischah** [comment]
Hej @addyosmani, Could you ping Googles domains team again. We would love to get rid of Travis and GitHub pages. See #753

**Comment by Rowno** [comment]
GitHub Pages with custom domains now support HTTPS. Can someone on the team flip the switch? 🙏 

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by sholladay** [comment]
Just came here to remind people to get this done. :)

It's 2018 and Chrome is not happy about HTTP. "Not Secure" is what it thinks of the Yeoman site.

**Comment by mischah** [comment]
It took quite a while. But I’m happy to say that the DNS settings are updated and https://yeoman.io is now served securely via netlify 🎉
